language: generic
os: osx

env:
  global:
    # Branch (or any remote ref, i.e. pull/10/head) to fetch
    - BUILD_BRANCH=master
    # Commit tag/ref to checkout
    - BUILD_COMMIT=FETCH_HEAD

    # If set to non empty value then Orange3 is build from the checked-out
    # sources otherwise it is installed from PyPI (assuming BUILD_COMMIT
    # is the version tag)
    - BUILD_LOCAL=1

cache:
  ccache: true
  directories:
    - ~/Library/Caches/pip
    # cache used by build-macos-app.sh
    - ~/.cache/pkgs

before_install:
  - git clone -q --depth 20 https://github.com/biolab/orange3.git
  - cd orange3
  - git fetch origin $BUILD_BRANCH
  - git checkout $BUILD_COMMIT

install:
  - APP=/Applications/Orange3.app
  - if [[ -d $APP ]]; then rm -rf $APP; fi
  - |-
    if [[ $BUILD_LOCAL ]]; then
        PIP_ARGS=( --pip-arg={-r,../specs/macos/requirements.txt,./} );
    else
        PIP_ARGS=( --pip-arg={-r,../specs/macos/requirements.txt,Orange3==$BUILD_COMMIT} );
    fi
  - |-
    ./scripts/macos/build-macos-app.sh "${PIP_ARGS[@]}" "$APP"
  - |-
    ./scripts/macos/create-dmg-installer.sh --app "$APP" dist/Orange3.dmg
  - |-
    VERSION=$("$APP/Contents/MacOS/pip" show orange3 | grep -E '^Version: ' | cut -d ' ' -f 2)
  - mv dist/Orange3.dmg dist/Orange3-$VERSION.dmg
  - cd ..

script:
  # run the tests in the application's environment, but move it to a different
  # location first
  - mkdir -p ~/Applications
  - mv -f $APP ~/Applications/
  - APP=( ~/Applications/Orange3.app )
  - $APP/Contents/MacOS/python --version
  - $APP/Contents/MacOS/pip --version
  - $APP/Contents/MacOS/pip freeze

  # Don't even ask
  - export ORANGE_DEPRECATIONS_ERROR=1
  - export PYTHONWARNINGS=module
  - $APP/Contents/MacOS/python -Xfaulthandler -m unittest -v Orange.tests Orange.widgets.tests


after_success:
  - shasum -a 256 orange3/dist/Orange3-*.dmg
  - echo $(curl -fS --upload-file orange3/dist/Orange3-*.dmg https://transfer.sh/)
