image: Visual Studio 2019

environment:
  global:
    # git repo from which to pull orange3 sources
    REPO: https://github.com/biolab/orange3.git
    # Branch/ref from which to pull
    BUILD_BRANCH: master
    # Commit ref/tag to checkout
    BUILD_COMMIT: 3.29.2

    # Build the package locally or use the build packages from
    # conda-forge / PyPI. The BUILD_COMMIT must match the package version
    # to build.
    # Comment/override this if building release versions.
    BUILD_LOCAL: 

    PIP_DISABLE_PIP_VERSION_CHECK: 1
    # build env dependencies for building orange3 wheels or any of its
    # dependencies that do not have wheels available
    BUILD_DEPS: wheel==0.29.0 pip~=19.0

  # Note the python version here refers to the one included in the installer
  # not the one used for building/packaging
  matrix:
    - PYTHON_VERSION: '3.8.8'
      PLATTAG: win_amd64
      CONDA: C:\Miniconda37-x64\Scripts\conda
      PYTHON: C:\Miniconda37-x64\python
      MINICONDA_VERSION: 'py38_4.9.2'
      CONDA_BUILD_VERSION: '3.18.*'
      CONDA_USE_ONLY_TAR_BZ2: "1"
      CONDA_SPEC_FILE:
      # CONDA_SPEC_FILE: ..\specs\win\conda-spec.txt

    - PYTHON_VERSION: '3.8.8'
      PLATTAG: win_amd64
      ENVSPEC: ../specs/win/PY38.txt
      PYTHON: C:\Python38-x64

matrix:
  fast_finish: false

cache:
  - '%LOCALAPPDATA%\pip\Cache -> appveyor.yml'
  - '.cache -> appveyor.yml'

build_script:
  - git clone -q --depth 20 %REPO%
  - cd orange3
  - git fetch origin %BUILD_BRANCH%
  - git checkout %BUILD_COMMIT%

  - set "PATH_BEFORE_BUILD=%PATH%"
  - set "PATH=C:\msys64\usr\bin;C:\Program Files (x86)\NSIS;%PATH%"
  - pacman -S --noconfirm zip unzip
  - if not "%CONDA%" == "" ( rmdir /q /s "C:\Program Files (x86)\Windows Kits\10\include\wdf" )
  - if not "%CONDA%" == "" ( ..\ci\appveyor-conda-build.bat )
  - if "%CONDA%" == "" ( ..\ci\appveyor-build.bat )

  - for %%s in ( dist/Orange3*.exe ) do ( set "INSTALLER=%%s" )
  - echo INSTALLER = %INSTALLER%

  - set "PATH=%PATH_BEFORE_BUILD%"
  - cd ..

test_script:
  - mkdir installers
  # cleanup registry of anaconda reg keys
  - reg delete HKEY_LOCAL_MACHINE\Software\Python\ContinuumAnalytics /f || cd .
  - reg delete HKEY_CURRENT_USER\Software\Python\ContinuumAnalytics /f || cd .
  - dir orange3\dist
  # Install in silent mode. Output has to be piped somewhere so the installer
  # runs 'attached' to the console.
  - orange3\dist\%INSTALLER% /S /D=C:\test-install > nul
  # The venv and conda envs create different install layouts.
  - if "%CONDA%" == "" ( set "PYTHON=C:\test-install\Scripts\python" )
  - if not "%CONDA%" == "" ( set "PYTHON=C:\test-install\python" )
  - if not "%CONDA%" == "" ( ci\appveyor-make-portable.bat C:\test-install %CD%\installers\Orange.zip )
  - >-
    "%PYTHON%" --version
  - >-
    "%PYTHON%" -m pip --version
  - >-
    "%PYTHON%" -m pip list --format=freeze
  # Test that orange and all dependencies are installed in a consistent state
  - >-
    "%PYTHON%" -m pip install --no-index --no-cache-dir orange3

  # Run test suite in the installed environment.
  - set ORANGE_DEPRECATIONS_ERROR=1
  - set PYTHONWARNINGS=module
  - >-
    "%PYTHON%" -m unittest -v Orange.tests Orange.widgets.tests || cd .
  - move orange3\dist\%INSTALLER% installers\

  # Log the filename and the sha checksum
  - for /f %%s in ( 'sha256sum -b installers/%INSTALLER%' ) do ( set "CHECKSUM=%%s" )
  - echo INSTALLER = %INSTALLER%
  - echo SHA256    = %CHECKSUM%


artifacts:
  - path: installers\*
  - path: conda-pkgs\*
